### PR TITLE
extract upnp port mapping as a standalone application

### PR DESCRIPTION
**Pull request by benoitc**
Following our discussion on IRC this change extract the UPNP module from etorrent_core to make it available as a standalone application.

The upnp module is available on [benoitc/upnp](http://github.com/benoitc/upnp). 

Summary of changes:
- add new etorrent_upnp_sup supervisor to optionnaly start UPNP
- remove upnp code from etorrent
-  replace lhttpc by [hackney](http://github.com/benoitc/hackney) since the UPNP app is using hackney as well
- make changes to use latest cowboy with ranch

TODO:
- add proper license to the UPNP application. Let me know what you want for that.

Let me know if it needs some changes.

### CODE REVIEW

**Comment by jlouis** [comment]
Sorry for not going through this earlier. I'll do that ASAP.

**Comment by jlouis** [comment]
As for the LICENSE, BSD 2-clause or MIT 2.0 :)

**Comment by lemenkov** [comment]
Upvoting this. A generic library for dealing with upnp would be great.

**Comment by jlouis** [comment]
This is awesome work benoitc. Thank you!

**Pull request merged**
